title: One is All, All is One
description: Stella Qian Xu's blog
theme: just-the-docs

url: https://stellax.github.io
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
